### ISSUE TITLE
How do I disable it when not in use

### ISSUE THREAD

**Issue by denstiny** [joshua7v/coc-comrade#3]
Comrade is a very useful plugin. I like it very much

**Comment by krmmzs** [comment]
You can disable specific plugins via Coclist extensions:
[https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#manage-extensions-with-coclist](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#manage-extensions-with-coclist)

**Comment by denstiny** [comment]
1 year apart

**Comment by denstiny** [comment]
I 've moved to lsp
